-- local utils = require('.utils')
-- require('relay-test.relay-test')
-- _G.send = spy.new(function() end)
-- _G.id = 'mock-process-id'

-- describe("relay-test", function()
--   it("should add handlers", function()
--     local handlers = { 'GET', 'GET-Result', 'POST', 'POST-Result' }
--     for _, name in ipairs(handlers) do
--       local handler = utils.find(
--         function (val) return val.name == name and val.pattern == name end,
--         _G.Handlers.list
--       )
--       assert.is_not_nil(handler)
--     end
--   end)

--   it('throws if url is missing in GET', function ()
--     local GET_handler = utils.find(
--       function (val) return val.name == 'GET' and val.pattern == 'GET' end,
--       _G.Handlers.list
--     )
--     assert.is_not_nil(GET_handler)
--     assert.has_error(function ()
--       GET_handler.handle({ from = 'tester' })
--     end, 'URL tag is required for GET request')
--   end)

--   it('sends message to /~relay@1.0 device on GET', function ()
--     local url = 'https://arweave.net'
--     local GET_handler = utils.find(
--       function (val) return val.name == 'GET' and val.pattern == 'GET' end,
--       _G.Handlers.list
--     )
--     assert.is_not_nil(GET_handler)
--     GET_handler.handle({ from = 'tester', url = url })
--     assert.spy(_G.send).was.called_with({
--       target = _G.id,
--       ['relay-path'] = url,
--       resolve = '~relay@1.0/call/~patch@1.0',
--       action = 'GET-Result'
--     })
--   end)
-- end)
